---
layout:     post
title:      协程与xpcall
date:       2019-6-25
author:     myc
header-img: img/post-bg-coffee.jpeg
catalog: true
tags:
    - 协程
    - 元表

---

# 协程与xpcall
在移植busted测试框架的时候，发现不能在测试用例里面调用协程的yield,核心原因是每个用例是运行在xpcall内，此时调用yield会报错

`attempt to yield across metamethod/C-call boundary`

示例代码

```lua

	local func = function()
		print("xpcall xxx");
	    coroutine.yield()--挂起
	    print("yield");
	end

	local funcList = {func,func,func}
	function run()
	    local co = coroutine.create(function( ... )
	        xpcall(function( ... )
	           print("xpcall xxx");
	           coroutine.yield()--挂起
	           print("yield");
	        end, function(errMsg)
	            print(errMsg) -- 触发异常 attempt to yield across metamethod/C-call boundary
	        end)
	    end)
	    coroutine.resume(co)
	end
	run()
```
## 想要达到目标
 * 能捕获异常
 * 能调用协程yield
