---
layout:     post
title:      协程与xpcall
date:       2019-6-25
author:     myc
header-img: img/post-bg-coffee.jpeg
catalog: true
tags:
    - 协程
    - 元表

---

# xpcall内部调用coroutine.yield(···)
在移植busted测试框架的时候，发现不能在测试用例里面调用协程的yield,核心原因是每个用例是运行在xpcall内，此时调用yield会报错

`attempt to yield across metamethod/C-call boundary`

示例代码

```lua
	function run()
	    local co = coroutine.create(function( ... )
	        xpcall(function( ... )
	           print("xpcall xxx");
	           coroutine.yield()--挂起
	           print("yield");
	        end, function(errMsg)
	            print(errMsg) -- 触发异常 attempt to yield across metamethod/C-call boundary
	        end)
	    end)
	    coroutine.resume(co)
	end
	run()
```

